### ISSUE TITLE
Disconnecting due timeout

### ISSUE THREAD

**Issue by RobDeFlop** [c0nnex/PureVoice#2]
I ported the GTMP PureVoice example to RageMP and got following issue:
PureVoice let the player timeout after approx. 5sec. Is there any possibility to avoid this?

**Comment by c0nnex** [comment]
You will need to call/refresh the WebConnect every 10 seconds, else the plugin will assume that GTA has crashed and disconnect/move the player.

**Comment by RobDeFlop** [comment]
Fixed. Thanks a lot!
